/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndktest_cg_com_ndktest_NdkUtils */

#ifndef _Included_ndktest_cg_com_ndktest_NdkUtils
#define _Included_ndktest_cg_com_ndktest_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndktest_cg_com_ndktest_NdkUtils
 * Method:    getStrinFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndktest_cg_com_ndktest_NdkUtils_getStrinFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
